#trash
command /trash:
    trigger:
        open chest with 6 row named "TRASH" to player
        exit
#craft
command /craft:
    aliases:/c
    trigger:
        open workbench to player
        exit

on bed enter:
	set time to 6:00

#
command /opp [<username>]
	trigger:
		if %arg-1% is "eringi_riri":
			execute console command "/op eringi_riri"
		if %arg-1% is "eringi_ririri":
			execute console command "/op eringi_ririri"
		
